### ISSUE TITLE
Jermacraft Copypasta debt removed incorrectly

### ISSUE THREAD

**Issue by Fallendorf** [JermaSites/JermaDebt#28]
The deal was for -1 billion, with 50 million added for bad impressions, adding up to -950 million.
https://www.twitch.tv/videos/861510275?t=03h10m44s

**Comment by poespas** [comment]
Good thing we have the debt accountants.

**Comment by s-crypt** [comment]
He said 500m for each, he misspoke once but several other times he stated correctly.

**Comment by Fallendorf** [comment]
Chat clearly agrees to subtract 950 million

**Comment by s-crypt** [comment]
And 950m was subtracted. 500m for Simpsons, and 450m (he agreed -50m for a bad impression) for the family guy ones, hence: 
![image](https://user-images.githubusercontent.com/41712656/104120197-d1769800-52e9-11eb-85b2-2b6940aeb02d.png)
Pardon, but I don't see the error?

**Comment by Fallendorf** [comment]
Ah, it seems I was confused that the two were seperate listings. Thank you for clarification.
