### ISSUE TITLE
Tiny grammar error

### ISSUE THREAD

**Issue by Erfaniom** [JermaSites/JermaDebt#36]
I don't wanna be that guy or a grammar Nazi but in this paragraph:
"Jerma985 then proceeded miss the next shot he took. This brings his debt to chat to an original two and a half billion US dollars."
Instead of: "Jerma985 then proceeded miss the next shot he took."
It should be: "Jerma985 then proceeded to miss the next shot he took."
As I said it's a tiny mistake but it is really on my nerves so i would appreciate it if you fix it :)

**Comment by s-crypt** [comment]
Thanks! Fixed! 😄
