### ISSUE TITLE
Shouldn't 1,000,000,000 be taken off the debt? 

### ISSUE THREAD

**Issue by ErwinG01** [JermaSites/JermaDebt#39]
https://www.youtube.com/watch?v=EhxUNbq5Vuo

**Comment by poespas** [comment]
As the rules states, the chat decides what counts and what does not. There was a good only 20 seconds inbetween jerma proposing this debt-proposition, and fulfilling this, thus not enough time for chat to decide this.

**Comment by s-crypt** [comment]
This was clearly a joke as he did not give enough time, like what @poespas said.
