### ISSUE TITLE
Re: Jerma Daily Routine

### ISSUE THREAD

**Issue by phaenixC** [JermaSites/JermaDebt#41]
[Outrage is brewing, I got someone to make a MEME for me](https://www.reddit.com/r/jerma985/comments/lmn4kv/proof_of_debt_fraud_this_is_an_outrage_psycho/) 

I think it's time to review the evidence, and look at all the upvotes and upset redditors.

**Comment by s-crypt** [comment]
Until this gains more traction, nothing will be done. I will not go against the will of chat. 
Rally chat behind you and change will come.
