### ISSUE TITLE
1,000,000,000 off debt / 350,000 added to debt

### ISSUE THREAD

**Issue by Maplejavas** [JermaSites/JermaDebt#43]
Site hasn't even been updated in a while but these 2 are ones that havent been added to the debt counter;

Slime Rancher - 1,000,000,000 off debt for jerma shooting a pink plort into the selling funnel from a long distance
https://youtu.be/EhxUNbq5Vuo

Wonders of Archeology - Jerma buys Grottobeasts.com and the IP for 350,000$
https://youtu.be/tVi9cx2_C98

**Comment by s-crypt** [comment]
Deals are made through the consensus of chat, and no consensus was made for the slime rancher. Also it was a bit, he did this a couple times. When he proposes a real deal, he takes time to make sure chat is on board.

I am unsure about grottobeasts adding to the debt for now. I will ask around and see what the community thinks

**Comment by s-crypt** [comment]
My initial reaction from the discord is no. It is seen as more of a 'company expense' for entertainment, than a personal bet. There are no streams until april so we will have to see what twitch chat says, but for now it is not being added.
If you disagree, please let me know and explain your reasoning.

**Comment by Maplejavas** [comment]
I guess that makes sense, was wondering if anything was being changed to the debt since its been since February since an update to the amount
