### ISSUE TITLE
Some debt removed for monkey video on Darkest Dungeons 11 stream

### ISSUE THREAD

**Issue by TacoTheDank** [JermaSites/JermaDebt#48]
He said either 100 million or 250 million, something like that. He didn't exactly go hard on a specific number, so would it be considered a real deal? He did commit to the bit and spent at least a few minutes on it.

He also did a fart (might've been fake) with echo and claimed the debt was cleared lol.

Opinions?

**Comment by s-crypt** [comment]
250M has been removed.

**Comment by TacoTheDank** [comment]
Very well. May this psycho streamer fulfill his payment one day.
