### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by TheMemeSniper** [JermaSites/JermaDebt#53]
doesn't have to be complex, just a blank page with the sum of money jerma owes will be good

**Comment by TheMemeSniper** [comment]
thanks!

**Comment by TheMemeSniper** [comment]
![image](https://user-images.githubusercontent.com/67394719/215398559-b25fd3b4-c85c-4068-b326-d8e2fd927d8d.png)

slight problem with that csv

**Comment by s-crypt** [comment]
Something must be up with your Libreoffice Calc import settings or how it reads CSV files. Opens just fine for me in both notepad and excel.

**Comment by TheMemeSniper** [comment]
wait whoops don't listen to me that's just my spaghetti code messing with the formatting 😓
